// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkn9Gd7_HzKyH9dVtdD8cHh4N3A3PUbGc',
    appId: '1:207361568852:web:08ff4a16d39c251cd7fdc1',
    messagingSenderId: '207361568852',
    projectId: 'chat-app-908b7',
    authDomain: 'chat-app-908b7.firebaseapp.com',
    storageBucket: 'chat-app-908b7.appspot.com',
    measurementId: 'G-D80EP2JRJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGZTGIKNLnQn61c_A7L9BpRZSFZ_kynyQ',
    appId: '1:207361568852:android:21e6a73118493f3dd7fdc1',
    messagingSenderId: '207361568852',
    projectId: 'chat-app-908b7',
    storageBucket: 'chat-app-908b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApo_8KSgj7zKHG25ET7jOScHa3bh54SMg',
    appId: '1:207361568852:ios:aa3fd756fc62edeed7fdc1',
    messagingSenderId: '207361568852',
    projectId: 'chat-app-908b7',
    storageBucket: 'chat-app-908b7.appspot.com',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApo_8KSgj7zKHG25ET7jOScHa3bh54SMg',
    appId: '1:207361568852:ios:aa3fd756fc62edeed7fdc1',
    messagingSenderId: '207361568852',
    projectId: 'chat-app-908b7',
    storageBucket: 'chat-app-908b7.appspot.com',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkn9Gd7_HzKyH9dVtdD8cHh4N3A3PUbGc',
    appId: '1:207361568852:web:c56fa141a6e1c3c1d7fdc1',
    messagingSenderId: '207361568852',
    projectId: 'chat-app-908b7',
    authDomain: 'chat-app-908b7.firebaseapp.com',
    storageBucket: 'chat-app-908b7.appspot.com',
    measurementId: 'G-XZ8R48995X',
  );
}
